# Pre-commit hooks configuration for QuizMaster Backend
# This prevents syntax errors and code quality issues from being committed
#
# To set up:
#   pip install pre-commit
#   pre-commit install
#
# To run manually:
#   pre-commit run --all-files

repos:
  # Built-in hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-python-ast  # Critical: Checks Python syntax
      - id: check-docstring-first
      - id: debug-statements
      - id: mixed-line-ending

  # Python-specific linting
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3
        exclude: ^(alembic/versions/|\.venv/)

  # Import sorting
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: ^(alembic/versions/|\.venv/)

  # Custom quality check hook
  - repo: local
    hooks:
      - id: code-quality-check
        name: Code Quality Check
        entry: python scripts/code_quality_check.py
        language: system
        types: [python]
        pass_filenames: false
        always_run: true 