version: '3.8'

services:
  quiz-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: quiz-app-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      # Database Configuration
      - DATABASE_URL=${DATABASE_URL}
      - DIRECT_URL=${DIRECT_URL:-}
      
      # Supabase Configuration  
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - SUPABASE_STORAGE_BUCKET=${SUPABASE_STORAGE_BUCKET:-quiz-images}
      
      # JWT Configuration
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_ALGORITHM=${JWT_ALGORITHM:-HS256}
      - JWT_ACCESS_TOKEN_EXPIRE_MINUTES=${JWT_ACCESS_TOKEN_EXPIRE_MINUTES:-30}
      
      # OTPLESS Configuration
      - OTPLESS_APP_ID=${OTPLESS_APP_ID}
      - OTPLESS_CLIENT_ID=${OTPLESS_CLIENT_ID}
      - OTPLESS_CLIENT_SECRET=${OTPLESS_CLIENT_SECRET}
      # - OTPLESS_WEBHOOK_SECRET=${OTPLESS_WEBHOOK_SECRET}
      
      # Application Configuration
      - APP_NAME=${APP_NAME:-QuizMaster by Jazzee}
      - APP_VERSION=${APP_VERSION:-1.0.0}
      - DEBUG=${DEBUG:-False}
      - CORS_ORIGINS=${CORS_ORIGINS}
      
      # # Email Configuration
      # - SMTP_HOST=${SMTP_HOST:-smtp.gmail.com}
      # - SMTP_PORT=${SMTP_PORT:-587}
      # - SMTP_USERNAME=${SMTP_USERNAME:-}
      # - SMTP_PASSWORD=${SMTP_PASSWORD:-}
      # - FROM_EMAIL=${FROM_EMAIL:-}
      
      # Frontend Configuration
      - FRONTEND_URL=${FRONTEND_URL}
      
      # Health Check Configuration
      - HEALTH_CHECK_URL=${HEALTH_CHECK_URL:-http://localhost:8000/health}
      
      # Security
      - BCRYPT_ROUNDS=${BCRYPT_ROUNDS:-12}
      
    volumes:
      # Mount uploads directory for file persistence
      - ./uploads:/app/uploads
      
    networks:
      - quiz-network
      
    healthcheck:
      test: ["CMD", "curl", "-f", "${HEALTH_CHECK_URL:-http://localhost:8000/health}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  quiz-network:
    driver: bridge 